import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { FaCalendarAlt, FaChartLine, FaTimesCircle, FaTicketAlt } from "react-icons/fa";
const API = import.meta.env.VITE_API_URL || "http://localhost:5000";

export default function UserDashboard() {
  const [bookings, setBookings] = useState([]), [error, setError] = useState("");
  const token = localStorage.getItem("accessToken");
  useEffect(() => { fetch(`${API}/bookings?limit=100`, { headers: { Authorization: `Bearer ${token}` } }).then(async r => { const j = await r.json(); if (!r.ok || !j.status) throw Error(j.message); return j; }).then(j => setBookings(j.data)).catch(e => setError(e.message || "Unable to load dashboard.")); }, []);
  const active = bookings.filter(b => !b.isCancel), tickets = active.reduce((total, b) => total + (b.booked_tickets || 0), 0), spending = active.reduce((total, b) => total + (b.total_ticket_amount || 0), 0);
  const upcoming = active.filter(b => b.event?.date && new Date(b.event.date) >= new Date()).length;
  const stats = [["Booked Tickets", tickets, <FaTicketAlt />, "text-cyan-400"], ["Upcoming Events", upcoming, <FaCalendarAlt />, "text-purple-400"], ["Cancelled Bookings", bookings.filter(b => b.isCancel).length, <FaTimesCircle />, "text-pink-400"], ["Total Spending", `₹${spending.toLocaleString("en-IN")}`, <FaChartLine />, "text-green-400"]];
  const recent = useMemo(() => [...bookings].sort((a,b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0,5), [bookings]);
  return <div><div className="flex flex-col sm:flex-row justify-between gap-4 mb-8"><div><h1 className="text-3xl font-black">My Dashboard</h1><p className="text-slate-400 mt-2">Your real event bookings and activity.</p></div><Link to="/events" className="bg-cyan-500 px-5 py-3 rounded-xl font-bold text-center">Explore Events</Link></div>{error && <p className="text-red-400 mb-5">{error}</p>}<div className="grid md:grid-cols-2 xl:grid-cols-4 gap-6 mb-10">{stats.map(([label,value,icon,color]) => <div key={label} className="bg-white/5 border border-white/10 rounded-3xl p-6"><div className={`${color} text-3xl mb-5`}>{icon}</div><h3 className="text-3xl font-black mb-2">{value}</h3><p className="text-slate-400">{label}</p></div>)}</div><div className="bg-white/5 border border-white/10 rounded-3xl p-8"><div className="flex justify-between gap-4 mb-7"><h3 className="text-2xl font-bold">Recent Booking History</h3><Link to="/dashboard/my-tickets" className="text-cyan-400">View all tickets</Link></div><div className="space-y-4">{recent.map(b => <div key={b._id} className="flex flex-col sm:flex-row justify-between gap-4 bg-slate-900 rounded-2xl p-5 border border-white/10"><div><h4 className="font-semibold">{b.event?.title || "Event"}</h4><p className="text-slate-400 text-sm mt-1">Booked on {new Date(b.createdAt).toLocaleDateString()} · {b.booked_tickets} {b.ticket_type} ticket(s)</p></div><div className="sm:text-right"><p className="font-bold text-cyan-400">₹{b.total_ticket_amount}</p><p className={`text-sm ${b.isCancel ? "text-red-400" : "text-green-400"}`}>{b.isCancel ? "Cancelled" : "Booked"}</p></div></div>)}{!recent.length && !error && <p className="text-slate-400">No bookings yet. Explore events to book your first ticket.</p>}</div></div></div>;
}
