import { useEffect, useMemo, useState } from "react";
import { FaDownload, FaSearch, FaTicketAlt, FaUsers } from "react-icons/fa";
const API = import.meta.env.VITE_API_URL || "http://localhost:5000";

export default function Attendees() {
  const [bookings, setBookings] = useState([]), [search, setSearch] = useState(""), [type, setType] = useState("all"), [error, setError] = useState("");
  const token = localStorage.getItem("adminAccessToken");
  useEffect(() => { fetch(`${API}/bookings/get-all-bookings?limit=100`, { headers: { Authorization: `Bearer ${token}` } }).then(async r => { const j = await r.json(); if (!r.ok || !j.status) throw Error(j.message); return j; }).then(j => setBookings(j.data)).catch(e => setError(e.message || "Unable to load attendees.")); }, []);
  const rows = useMemo(() => bookings.filter(b => { const text = `${b.attendee?.name || ""} ${b.attendee?.email || ""} ${b.event?.title || ""}`.toLowerCase(); return text.includes(search.toLowerCase()) && (type === "all" || b.ticket_type === type); }), [bookings, search, type]);
  const active = bookings.filter(b => !b.isCancel), tickets = active.reduce((sum, b) => sum + (b.booked_tickets || 0), 0);
  const exportCsv = () => { const header = "Name,Email,Event,Ticket type,Tickets,Amount,Status,Booking date"; const lines = rows.map(b => [b.attendee?.name, b.attendee?.email, b.event?.title, b.ticket_type, b.booked_tickets, b.total_ticket_amount, b.isCancel ? "Cancelled" : "Booked", new Date(b.createdAt).toLocaleDateString()].map(v => `"${String(v || "").replaceAll('"', '""')}"`).join(",")); const url = URL.createObjectURL(new Blob([[header, ...lines].join("\n")], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "event-attendees.csv"; link.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-7"><div className="flex flex-col sm:flex-row justify-between gap-4"><div><h1 className="text-4xl font-black">Attendees & Bookings</h1><p className="text-slate-400 mt-2">Real bookings for events created by you.</p></div><button onClick={exportCsv} className="bg-cyan-500 px-5 py-3 rounded-xl font-semibold flex gap-2 items-center"><FaDownload /> Export CSV</button></div><div className="grid md:grid-cols-3 gap-5"><Stat label="Active bookings" value={active.length} /><Stat label="Total tickets sold" value={tickets} color="text-green-400" /><Stat label="Cancelled bookings" value={bookings.filter(b=>b.isCancel).length} color="text-yellow-400" /></div><div className="flex flex-col md:flex-row gap-3"><div className="relative flex-1"><FaSearch className="absolute left-4 top-4 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search attendee, email, or event..." className="w-full bg-slate-900 border border-white/10 rounded-xl py-3 pl-11 pr-4"/></div><select value={type} onChange={e=>setType(e.target.value)} className="bg-slate-900 border border-white/10 rounded-xl p-3"><option value="all">All ticket types</option><option value="general">General</option><option value="premium">Premium</option></select></div>{error&&<p className="text-red-400">{error}</p>}<div className="bg-white/5 border border-white/10 rounded-3xl overflow-x-auto"><table className="w-full text-left"><thead className="border-b border-white/10 text-slate-400"><tr><th className="p-4">Attendee</th><th className="p-4">Event</th><th className="p-4">Ticket</th><th className="p-4">Amount</th><th className="p-4">Booked on</th><th className="p-4">Status</th></tr></thead><tbody>{rows.map(b=><tr key={b._id} className="border-b border-white/5"><td className="p-4"><b>{b.attendee?.name||"Deleted user"}</b><br/><span className="text-slate-400 text-sm">{b.attendee?.email||"No email"}</span></td><td className="p-4">{b.event?.title||"Deleted event"}<br/><span className="text-slate-400 text-sm">{b.event?.venue||""}</span></td><td className="p-4 capitalize"><span className="px-3 py-1 rounded-full bg-purple-500/20 text-purple-300">{b.ticket_type}</span><br/><span className="text-slate-400 text-sm">{b.booked_tickets} ticket(s)</span></td><td className="p-4">₹{b.total_ticket_amount}</td><td className="p-4">{new Date(b.createdAt).toLocaleDateString()}</td><td className="p-4"><span className={b.isCancel?"text-red-400":"text-green-400"}>{b.isCancel?"Cancelled":"Booked"}</span></td></tr>)}{!rows.length&&<tr><td colSpan="6" className="p-8 text-center text-slate-400">No bookings found for your events.</td></tr>}</tbody></table></div></div>;
}
function Stat({label,value,color="text-cyan-400"}) { return <div className="bg-white/5 border border-white/10 rounded-2xl p-5"><div className="flex gap-3 items-center"><FaUsers className={color}/><div><b className={`text-3xl ${color}`}>{value}</b><p className="text-slate-400">{label}</p></div></div></div>; }
