import { useEffect, useMemo, useState } from "react";
import { FaCalendarAlt, FaMoneyBillWave, FaTicketAlt, FaUsers } from "react-icons/fa";
const API = import.meta.env.VITE_API_URL || "http://localhost:5000";

export default function Dashboard() {
  const [events, setEvents] = useState([]), [bookings, setBookings] = useState([]), [error, setError] = useState("");
  const token = localStorage.getItem("adminAccessToken");
  useEffect(() => { async function load() { try { const headers = { Authorization: `Bearer ${token}` }; const [eventsRes, bookingsRes] = await Promise.all([fetch(`${API}/events/my?limit=100`, { headers }), fetch(`${API}/bookings/get-all-bookings?limit=100`, { headers })]); const [eventsJson, bookingsJson] = await Promise.all([eventsRes.json(), bookingsRes.json()]); if (!eventsRes.ok || !eventsJson.status) throw Error(eventsJson.message || "Unable to load events."); if (!bookingsRes.ok || !bookingsJson.status) throw Error(bookingsJson.message || "Unable to load bookings."); setEvents(eventsJson.data); setBookings(bookingsJson.data); } catch (e) { setError(e.message || "Unable to load dashboard."); } } load(); }, []);
  const active = bookings.filter(b => !b.isCancel), tickets = active.reduce((sum,b) => sum + (b.booked_tickets || 0), 0), revenue = active.reduce((sum,b) => sum + (b.total_ticket_amount || 0), 0);
  const stats = [{title:"Total Events",value:events.length,icon:<FaCalendarAlt/>,color:"text-cyan-400"},{title:"Active Events",value:events.filter(e=>!e.isCancel).length,icon:<FaUsers/>,color:"text-green-400"},{title:"Tickets Sold",value:tickets,icon:<FaTicketAlt/>,color:"text-purple-400"},{title:"Revenue",value:`₹${revenue.toLocaleString("en-IN")}`,icon:<FaMoneyBillWave/>,color:"text-yellow-400"}];
  const recentEvents = useMemo(() => [...events].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5), [events]); const recentBookings = useMemo(() => [...bookings].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,5), [bookings]);
  return <div className="space-y-9"><div><h1 className="text-4xl font-black">Dashboard Overview</h1><p className="text-slate-400 mt-2">Live performance data for your events.</p></div>{error&&<p className="text-red-400">{error}</p>}<div className="grid md:grid-cols-2 xl:grid-cols-4 gap-5">{stats.map(s=><div key={s.title} className="bg-white/5 border border-white/10 rounded-3xl p-6"><div className={`${s.color} text-3xl mb-4`}>{s.icon}</div><h3 className="text-3xl font-black mb-2">{s.value}</h3><p className="text-slate-400">{s.title}</p></div>)}</div><div className="grid lg:grid-cols-2 gap-6"><section className="bg-white/5 border border-white/10 rounded-3xl p-6"><h2 className="text-2xl font-bold mb-5">Recent Events</h2><div className="space-y-3">{recentEvents.map(e=><div key={e._id} className="bg-slate-900 rounded-2xl p-4 flex justify-between gap-3"><div><b>{e.title}</b><p className="text-sm text-slate-400">{e.venue} · {e.date}</p></div><span className={e.isCancel?"text-red-400":"text-green-400"}>{e.isCancel?"Cancelled":"Active"}</span></div>)}{!recentEvents.length&&<p className="text-slate-400">No events created yet.</p>}</div></section><section className="bg-white/5 border border-white/10 rounded-3xl p-6"><h2 className="text-2xl font-bold mb-5">Recent Bookings</h2><div className="space-y-3">{recentBookings.map(b=><div key={b._id} className="bg-slate-900 rounded-2xl p-4 flex justify-between gap-3"><div><b>{b.attendee?.name||"Guest"}</b><p className="text-sm text-slate-400">{b.event?.title||"Event"} · {b.booked_tickets} {b.ticket_type}</p></div><span className={b.isCancel?"text-red-400":"text-cyan-300"}>{b.isCancel?"Cancelled":`₹${b.total_ticket_amount}`}</span></div>)}{!recentBookings.length&&<p className="text-slate-400">No bookings yet.</p>}</div></section></div></div>;
}
