import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router";
const API = import.meta.env.VITE_API_URL || "http://localhost:5000";
const initial = { title:"", desc:"", total_general_tickets:"", total_premium_tickets:"", general_tickets_price:"", premium_tickets_price:"", date:"", time:"", venue:"", category:"Music", highlights:"", organizer:"" };
export default function EventForm() {
 const [form,setForm]=useState(initial),[banner,setBanner]=useState(null),[error,setError]=useState(""),[message,setMessage]=useState(""); const [params]=useSearchParams(); const id=params.get("id"), nav=useNavigate(), token=localStorage.getItem("adminAccessToken");
 useEffect(()=>{ if(!id)return; fetch(`${API}/events/${id}`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(j=>{if(!j.status)throw Error(j.message); const e=j.data; setForm({...e,highlights:(e.highlights||[]).join(", ")});}).catch(e=>setError(e.message));},[id]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const expired=message=>{if(message==="Invalid token"||message==="token not found"){localStorage.removeItem("adminAccessToken");localStorage.removeItem("adminUser");nav("/admin/login");return true;}return false;};
 const submit=async e=>{e.preventDefault();setError("");setMessage("Saving...");try{if(!id&&!banner)throw Error("Please choose an event banner.");const body=new FormData();Object.entries(form).forEach(([k,v])=>body.append(k,k==="highlights"?JSON.stringify(String(v||"").split(",").map(x=>x.trim()).filter(Boolean)):v));if(banner)body.append("thumbnail",banner);const r=await fetch(id?`${API}/events/${id}`:`${API}/events`,{method:id?"PATCH":"POST",headers:{Authorization:`Bearer ${token}`},body});const j=await r.json();if(!r.ok||!j.status)throw Error(j.message||"Unable to save event.");nav("/events");}catch(e){if(!expired(e.message)){setMessage("");setError(e.message||"Unable to save event.");}}};
 const fields=[["title","Event name"],["venue","Venue"],["date","Date"],["time","Time"],["organizer","Organizer (first and last name)"],["total_general_tickets","General tickets"],["general_tickets_price","General ticket price"],["total_premium_tickets","Premium tickets"],["premium_tickets_price","Premium ticket price"]];
 return <form onSubmit={submit} className="max-w-4xl mx-auto space-y-6"><div><h1 className="text-4xl font-black">{id?"Edit Event":"Create New Event"}</h1><p className="text-slate-400 mt-2">Fill all event details, then save.</p></div><div className="bg-white/5 border border-white/10 rounded-3xl p-7 grid md:grid-cols-2 gap-5">{fields.map(([name,label])=><label key={name} className="space-y-2"><span>{label}</span><input required name={name} type={name.includes("tickets")||name.includes("price")?"number":name==="date"?"date":name==="time"?"time":"text"} value={form[name]||""} onChange={change} className="w-full bg-slate-900 border border-white/10 p-3 rounded-xl" /></label>)}<label className="space-y-2"><span>Category</span><select name="category" value={form.category} onChange={change} className="w-full bg-slate-900 border border-white/10 p-3 rounded-xl"><option>Music</option><option>Business</option><option>Technology</option><option>Gaming</option><option>Festival</option><option>Workshop</option></select></label><label className="space-y-2"><span>{id?"Replace banner (optional)":"Event banner"}</span><input required={!id} type="file" accept="image/*" onChange={e=>setBanner(e.target.files?.[0])} className="w-full bg-slate-900 border border-white/10 p-3 rounded-xl" />{id&&form.thumbnail&&<img src={form.thumbnail} alt="Current banner" className="mt-3 w-full h-24 object-cover rounded-xl" />}</label><label className="md:col-span-2 space-y-2"><span>Description</span><textarea required name="desc" value={form.desc||""} onChange={change} rows="5" className="w-full bg-slate-900 border border-white/10 p-3 rounded-xl" /></label><label className="md:col-span-2 space-y-2"><span>Highlights (separate with commas)</span><input name="highlights" value={form.highlights||""} onChange={change} className="w-full bg-slate-900 border border-white/10 p-3 rounded-xl" /></label></div>{error&&<p className="text-red-400">{error}</p>}{message&&<p className="text-cyan-300">{message}</p>}<div className="flex gap-4"><button className="bg-cyan-500 px-6 py-3 rounded-xl font-bold">{id?"Save Changes":"Create Event"}</button><button type="button" onClick={()=>nav("/events")} className="bg-slate-800 px-6 py-3 rounded-xl">Cancel</button></div></form>;
}
