import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router";
import { FaEdit, FaPlus, FaSearch, FaTrash } from "react-icons/fa";
const API = import.meta.env.VITE_API_URL || "http://localhost:5000";

export default function Events() {
  const [events, setEvents] = useState([]), [search, setSearch] = useState(""), [message, setMessage] = useState(""), [error, setError] = useState("");
  const navigate = useNavigate(); const token = localStorage.getItem("adminAccessToken");
  const load = async () => { try { const r = await fetch(`${API}/events/my?limit=15`, { headers: { Authorization: `Bearer ${token}` } }); const j = await r.json(); if (!r.ok || !j.status) throw Error(j.message); setEvents(j.data); } catch (e) { setError(e.message || "Unable to load events."); } };
  useEffect(() => { load(); }, []);
  const remove = async (id) => { if (!window.confirm("Delete this event?")) return; try { const r = await fetch(`${API}/events/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); const j = await r.json(); if (!r.ok || !j.status) throw Error(j.message); setEvents(events.filter(e => e._id !== id)); setMessage("Event deleted."); } catch (e) { setError(e.message || "Unable to delete event."); } };
  const filtered = useMemo(() => events.filter(e => `${e.title} ${e.category} ${e.venue}`.toLowerCase().includes(search.toLowerCase())), [events, search]);
  return <div className="space-y-7"><div className="flex justify-between items-center gap-4"><div><h1 className="text-4xl font-black">Manage Events</h1><p className="text-slate-400 mt-2">Create, edit and delete your real events.</p></div><button onClick={() => navigate("/create-event")} className="bg-cyan-500 px-5 py-3 rounded-xl font-semibold flex gap-2 items-center"><FaPlus /> Create Event</button></div><div className="grid grid-cols-2 gap-4"><div className="bg-white/5 border border-white/10 rounded-2xl p-5"><b className="text-3xl text-cyan-400">{events.length}</b><p className="text-slate-400">Total Events</p></div><div className="bg-white/5 border border-white/10 rounded-2xl p-5"><b className="text-3xl text-green-400">{events.filter(e => !e.isCancel).length}</b><p className="text-slate-400">Active Events</p></div></div><div className="relative"><FaSearch className="absolute left-4 top-4 text-slate-500" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search your events..." className="w-full bg-slate-900 border border-white/10 rounded-xl py-3 pl-11 pr-4" /></div>{message && <p className="text-green-400">{message}</p>}{error && <p className="text-red-400">{error}</p>}<div className="bg-white/5 border border-white/10 rounded-3xl overflow-x-auto"><table className="w-full text-left"><thead className="border-b border-white/10 text-slate-400"><tr><th className="p-4">Event</th><th className="p-4">Date & time</th><th className="p-4">Venue</th><th className="p-4">Category</th><th className="p-4">Actions</th></tr></thead><tbody>{filtered.map(e => <tr key={e._id} className="border-b border-white/5"><td className="p-4 font-semibold">{e.title}</td><td className="p-4">{e.date}<br/><span className="text-slate-400">{e.time}</span></td><td className="p-4">{e.venue}</td><td className="p-4">{e.category}</td><td className="p-4 flex gap-2"><button onClick={() => navigate(`/create-event?id=${e._id}`)} className="p-3 rounded-lg bg-yellow-500/20 text-yellow-300"><FaEdit /></button><button onClick={() => remove(e._id)} className="p-3 rounded-lg bg-red-500/20 text-red-300"><FaTrash /></button></td></tr>)}{!filtered.length && <tr><td colSpan="5" className="p-8 text-center text-slate-400">No events yet. Click Create Event to add one.</td></tr>}</tbody></table></div></div>;
}
